const standardChartDescriptions = {
  "Working Day":[
              ["Morning liturgy",[20,20],"munro"],
                [" - Well-defined start",[95,30],"top"],
                [" - Post in Mum's chat",[125,30],"top"],
                [" - Check this month's chart and scribbles doc",[155,30],"top"],
                [" - Feed burrds",[185,30],"top"],
                [" - Empty bins",[215,30],"top"],
                [" - Do washing",[245,30],"top"],
                [" - Check kitchen calendar",[275,30],"top"],
                [" - Kettlebell exercises",[305,30],"top"],
              ["Seize the first hour -",[20,120],"munro"],
                [" - 9:00 prayer",[110,140],"munro"],
                [" - LTL20",[110,200],"munro"],
                [" - LTL20",[110,260],"munro"],
                [" - LTL20",[110,320],"munro"],
              ["Mid-day liturgy",[400,20],"munro"],
                [" - Finance admin",[475,30],"top"],
                [" - Clear kitchen",[505,30],"top"],
                [" - 2 minutes recorded speaking",[535,30],"top"],
                [" - Rachmaninov",[565,30],"top"],
                [" - Debussy",[595,30],"top"],
              ["Seize the afternoon -",[400,120],"munro"],
                [" - 13 o'clock prayer",[490,140],"munro"],
                [" - LTL20",[490,200],"munro"],
                [" - LTL20",[490,260],"munro"],
                [" - LTL20",[490,320],"munro"],
              ["Miscellaneous...",[700,20],"munro"]
  ],
  "Default Friday":[
              ["Morning liturgy",[20,20],"munro"],
                [" - Morning prayer",[95,30],"top"],
                [" - Check this month's chart and scribbles doc",[125,30],"top"],
                [" - Feed burrds",[155,30],"top"],
                [" - Empty bins",[185,30],"top"],
                [" - Do washing",[215,30],"top"],
                [" - Check kitchen calendar",[245,30],"top"],
                [" - Kettlebell exercises",[275,30],"top"],
              ["Morning walk -",[20,120],"munro"],
                [" (e.g. >= Hoop Peas)",[110,140],"munro"],
              ["Mid-day liturgy",[400,20],"munro"],
                [" - Finance admin",[475,30],"top"],
                [" - Clear kitchen",[505,30],"top"],
                [" - Rachmaninov",[535,30],"top"],
                [" - Debussy",[565,30],"top"],
              ["Afternoon -",[400,120],"munro"],
                [" - Week retro",[490,140],"munro"],
                [" - Backlog refinement",[490,200],"munro"],
                [" - Sprint plonning",[490,260],"munro"],
              ["Miscellaneous...",[700,20],"munro"]
  ],
  "Activity Day":[
              ["The Excitement:",[20,20],"munro"],
              ["The prep -",[20,100],"munro"]
  ],
  "Devops Day":[
              ["Morning liturgy",[20,20],"munro"],
                [" - Well-defined start",[95,30],"top"],
                [" - Morning prayer",[125,30],"top"],
                [" - Check this month's chart and scribbles doc",[155,30],"top"],
                [" - Feed burrds",[185,30],"top"],
                [" - Empty bins",[215,30],"top"],
                [" - Do washing",[245,30],"top"],
                [" - Check kitchen calendar",[275,30],"top"],
                [" - Kettlebell exercises",[305,30],"top"],
              ["Mid-day liturgy",[400,20],"munro"],
                [" - Finance admin",[475,30],"top"],
                [" - Clear kitchen",[505,30],"top"],
                [" - Rachmaninov",[535,30],"top"],
                [" - Debussy",[565,30],"top"],
              ["Main actitities -",[400,120],"munro"],
                [" [one] ",[490,140],"munro"],
                [" [two] ",[490,200],"munro"],
                [" [three] ",[490,260],"munro"]
  ],
  "Sabbath":[
              ["Morning liturgy",[20,20],"munro"],
                [" - Morning prayer",[95,30],"top"],
                [" - Feed burrds",[125,30],"top"],
                [" - Do washing",[155,30],"top"],
                [" - Message Mum",[185,30],"top"],
                ["Gather locally",[100,100],"munro"],
                ["Review kitchen calendar",[100,200],"munro"],
                ["Review charts/sprints",[100,300],"munro"],
                ["Gather non-locally",[100,400],"munro"]
  ]
}